services:
  ev-plan-backend:
    build: ./backend
    ports:
      - 5000:5000
    volumes:
      - ./backend-uploads:/app/public/uploads
    environment:
      - MONGO_URI=mongodb://admin:admin@ev-plan-db:27017/event-planner?authSource=admin
    networks:
      - ev-plan-network
    depends_on:
      ev-plan-db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/v1/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: unless-stopped

  ev-plan-db:
    image: mongo:latest
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    volumes:
      - ./mongo-data:/data/db
    networks:
      - ev-plan-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  ev-plan-frontend:
    build: ./frontend
    ports:
      - 80:80
    networks:
      - ev-plan-network
    depends_on:
      ev-plan-backend:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: unless-stopped

networks:
  ev-plan-network:
    driver: bridge

volumes:
  mongo-data:
    driver: local
  backend-uploads:
    driver: local